header_ar = [
    "الصفحة الرئسية",
    "المشاريع",
    "حجز استشارة",
    "وظائف",
    "حول الشركة",
    "خدمات الشركة",
    "كادر الشركة",
]

header_en = [
    "Home",
    "Project",
    "Book a Consultation",
    "Jobs",
    "About US",
    "Services",
    "Our Team",
]

hero_en = {
    "title1": "ALASWAD FOR LUXURY DESIGN",
    "title2": "Engineering and design solutions",
    "subtitle": "This text is an example of text that can be replaced in the same space. This text was generated from "
                "the Arabic text generator, where you can generate such text or many other texts in addition to "
                "increasing the number of characters generated by the application.",
    "button": "Book an engineering consultation now",
}
hero_ar = {
    "title1": "الأسود للتصميم الفاخر و الحلول الهندسية",
    "title2": "الحلول الهندسية والتصميم",
    "subtitle": "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.",
    "button": "احجز استشارة  الهندسية الان",
}

footer_en = {
    "company": "Company",
    "title": "This text is an example of text that can be replaced in the same space.",
    "home": "Home",
    "project": "Project",
    "book": "Book a Consultation",
    "jobs": "Jobs",
    "support": "Support",
    "media": "Press media",
    "about": "About US",
    "vision": "Our Vision",
    "contact": "Contact US",
    "get": "Get in touch",
    "live_support": "Need live support?",
    "phone": "Toll Free Customer Care",
    "subscribe": "Subscribe to receive future updates",
    "newsletter": "Newsletter",
    "policy": "Policy",
    "copywrite": "© 2025 ALASWAD. All rights reserved"
}

footer_ar = {
    "company": "شركة",
    "title": "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى.",
    "home": "الصفحة الرئسية",
    "project": "المشاريع",
    "book": "حجز استشارة",
    "jobs": "الوظائف",
    "support": "الدعم",
    "media": "التواصل الاجتماعي",
    "about": "حول الشركة",
    "vision": "رؤية الشركة",
    "contact": "اتصال بنا",
    "get": "ابقى على تواصل",
    "live_support": "هل تحتاج إلى دعم مباشر؟",
    "phone": "خدمة العملاء المجانية",
    "subscribe": "اشترك لتلقي التحديثات المستقبلية",
    "newsletter": "النشرة الإخبارية",
    "policy": "سياسة الخصوصية",
    "copywrite": "© ALASWAD 2025 . All rights reserved"
}

service_en = {
    "title": "Services provided & Core Features including:",
    "subtitle": "This text is an example of text that can be replaced in the same space.",
    "service": "Crafted for startups",
    "service1": "High-quality Design",
    "service2": "All Essential Sections",
    "service3": "Speed Optimized",
    "service4": "Fully Customizable",
    "service5": "Regular Updates",
    "title1": "FEATURES",
}

service_ar = {
    "title": "الخدمات المقدمة & الميزات الأساسية بما في ذلك",
    "subtitle": "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة.",
    "service": "مُصممة للشركات الناشئة",
    "service1": "تصميم عالي الجودة",
    "service2": "جميع الأقسام الأساسية",
    "service3": "السرعة الأمثل",
    "service4": "قابلة للتخصيص بالكامل",
    "service5": "تحديثات منتظمة",
    "title1": "سمات",
}

prodcuts_en = {
    "title": "Latest Project & Articles From Our Blog",
    "subtitle": "This text is an example that can be replaced in the same space, where you can create this text from the Arabic text, where you can generate such text or other texts for other texts",
    "category": "interior design",
    "address": "Baghdad , Al-Karkh",
    "ptitle": "This text is an example that can be replaced in the same space"
}
prodcuts_ar = {
    "title": "أحدث المشاريع والمقالات من مدونتنا",
    "subtitle": "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى",
    "category": "التصميم الداخلي",
    "address": "بغداد ، الكرخ",
    "ptitle": "هذا النص هو مثال يمكن استبداله في نفس المساحة"
}

team_en = {
    "title": "The staff of the ِِAlaswd company",
    "subtitle": "This text is an example that can be replaced in the same space, where you can create this text from the Arabic text, where you can generate such text or other texts for other texts",
}

team_ar = {
    "title": "كادر العمل شركة الاسود ",
    "subtitle": "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى",
}

about_en = {
    "title": "Know Details About Our Company",
    "subtitle": "This text is an example that can be replaced in the same space, where you can create this text from the Arabic text, where you can generate such text or other texts for other texts",
    "about_us": "About Us",
    "mission": "Our Mission",
    "vision": "Our Vision",
    "about_title": "Al-Aswad Interior Design Company in Iraq",
    "about_contant": "Specialized in providing elegant and stunning interior design services for both residential and commercial projects. Our interior designers are well-experienced in different international styles. We also aim to build lasting relationships with our clients through strong communications and always customize charming and wonderful designs for your units as one of the best interior design companies in Turkey. Contact us further to find out why we are one of the best interior design companies",
    "mission_title": "This text is an example that can be replaced in the same space",
    "mission_contant": "This text is an example that can be replaced in the same space, where you can create this text from the Arabic text, where you can generate such text or other texts for other texts",
    "vision_title": "This text is an example that can be replaced in the same space",
    "vision_contant": "This text is an example that can be replaced in the same space, where you can create this text from the Arabic text, where you can generate such text or other texts for other texts",
}

about_ar = {
    "title": "تعرف على التفاصيل حول شركتنا",
    "subtitle": "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى",
    "about_us": "About Us",
    "mission": "Our Mission",
    "vision": "Our Vision",
    "about_title": "شركة الاسود للتصميم الداخلي في العراق",
    "about_contant": " متخصصة في تقديم خدمات التصميم الداخلي الأنيقة والمذهلة لكل من المشاريع السكنية والتجارية.يتمتع مصممو الديكور الداخلي لدينا بخبرة جيدة في الأساليب الدولية المختلفة. نهدف أيضًا إلى بناء علاقات دائمة مع عملائنا من خلال الاتصالات القوية وا  دائمًا تخصيص تصميمات ساحرة ورائعة لوحداتك كواحدة من أفضل شركات تصميم داخلي في تركيا. اتصل بنا أكثر لمعرفة سبب كوننا واحدة من أفضل شركات تصميم داخلي ",
    "mission_title": "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة",
    "mission_contant": "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى",
    "vision_title": "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة",
    "vision_contant": "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى",
}

consultation_en ={
    "title":"Book an engineering consultation",
    "subtitle":"You can submit an engineering consultation request through e-mail or from the information below",
    "email":"Email address",
    "phone":"Phone Number",
    "location":"Office Location",
     "name":"Your Name",
    "address":"Email Address",
    "subject":"Subject",
    "phone":"Phone (Optional)",
    "message":"Message",
    "send":"Send Message"
}

consultation_ar ={
    "title":"حجز استشارة هندسية ",
    "subtitle":"يمكنك تقديم طلب استشارة هندسية من خلال الايميل او من الاخلا الاستنارة ادناة",
    "email":"عنوان البريد الإلكتروني",
    "phone":"رقم التليفون",
    "location":"موقع المكتب",
    "name":"الاسم الكامل",
    "address":"عنوان البريد الالكتروني",
    "subject":"الموضوع",
    "phone":"رقم الهاتف",
    "message":"رسالة",
    "send":"ارسال الطلب"
}